version: '3.9'
services:
  mongo:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME: libdba
      - MONGO_INITDB_ROOT_PASSWORD: Lib!123
    ports:
      - 27017: 27017
